version: "3"
services:
    webnews:
        build: .
        ports:
            - 4444:4444
        env_file:
            - .env
        working_dir: /app
        volumes:
            - .:/app
        links:
            - database
            
    database:
        image: "mariadb"
        env_file:
          - .env
        expose:
          - '3306'